---
gcp_pd_csi_controller_replicas: 1
#gcp_pd_csi_driver_image_tag: "v1.4.0"

#csi_attacher_image_repo: "{{ kube_image_repo }}/sig-storage/csi-attacher"
#csi_attacher_image_tag: "v3.3.0"
#csi_provisioner_image_repo: "{{ kube_image_repo }}/sig-storage/csi-provisioner"
#csi_provisioner_image_tag: "v3.0.0"
#csi_snapshotter_image_repo: "{{ kube_image_repo }}/sig-storage/csi-snapshotter"
#csi_snapshotter_image_tag: "v5.0.0"
#csi_resizer_image_repo: "{{ kube_image_repo }}/sig-storage/csi-resizer"
#csi_resizer_image_tag: "v1.3.0"
#csi_node_driver_registrar_image_repo: "{{ kube_image_repo }}/sig-storage/csi-node-driver-registrar"
#csi_node_driver_registrar_image_tag: "v2.4.0"
